# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: flutter_md

description: >
  Markdown library written in Dart.
  It can parse and display Markdown.

version: 0.0.5

homepage: https://github.com/DoctorinaAI/md
repository: https://github.com/DoctorinaAI/md
issue_tracker: https://github.com/DoctorinaAI/md/issues

topics:
  - markdown
  - rendering
  - selectable
  - chatgpt
  - gemini

platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:

# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"
  markdown: ^7.3.0
  benchmark_harness: ^2.3.1
